spring:
  application:
    name: team3
  datasource:
    url: jdbc:mysql://localhost:3306/team3?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1004

server:
  port: 9001

mybatis:
  mapper-locations: classpath:mappers/*.xml